server: 
   port: 11011

spring: 
   rabbitmq: 
      host: 192.168.85.131
      port: 5672
      username: root
      password: root
   #禁止thymeleaf缓存（建议：开发环境设置为false，生成环境设置为true）
   thymeleaf: 
      cache: false

ymlValue: zuul