server:
   #port: 18111

spring:
   dataSource: 
      driver-class-name: com.mysql.jdbc.Driver
      #driver-class-name: com.mariadb.jdbc.Driver
      username: root
      password: root
      url: jdbc:mysql://127.0.0.1:3306/springCloud_PrivilegeServer?characterEncoding=UTF-8&useSSL=false
      #url: jdbc:mariadb://127.0.0.1:3306/springCloud_PrivilegeServer?characterEncoding=UTF-8
   jpa: 
      show-sql: true
   rabbitmq: 
      host: 192.168.85.131
      port: 5672
      username: root
      password: root
   #禁止thymeleaf缓存（建议：开发环境设置为false，生成环境设置为true）
   thymeleaf: 
      cache: false
hystrix: 
   command: 
      default: 
         execution: 
            isolation: 
               thread: 
                  #timeoutInMillisenconds：3000
                  timeoutInMilliseconds: 3000
                   
logging:
   config: classpath:logback.xml
   path: d:/logs

   
ymlValue: ymlValue11223334444555
 
 
